import * as images from '../assets'

export const giftList = [
  {
    id: 1,
    image: images.cribLight,
    name: 'Luz de Berço Glow, Maxi-Cosi, White',
    price: 229,
    quantity: 0,
  },
  {
    id: 2,
    image: images.cueiro,
    name: 'Cueiro Estampado, Papi Textil, Azul, 1.0mx80cm, Pacote de 3',
    price: 39.49,
    quantity: 0,
    showInCarousel: true,
  },
  {
    id: 3,
    image: images.socks,
    name: 'Kit 12 Pares Meia Infantil Antiderrapante',
    price: 49.9,
    quantity: 0,
    showInCarousel: true,
  },
  {
    id: 4,
    image: images.thermometer,
    name: 'Termômetro Digital Gtech Clínico Branco, G-Tech',
    price: 17.18,
    quantity: 0,
    showInCarousel: true,
  },
  {
    id: 5,
    image: images.diaperHolder,
    name: 'Trocador e Porta Fraldas, Azul, 66 x 40 cm',
    price: 30,
    quantity: 0,
    showInCarousel: true,
  },
  {
    id: 6,
    image: images.babyCart,
    name: '1 Cota - Carrinho de Bebe',
    price: 50,
    quantity: 0,
    showInCarousel: true,
  },
  {
    id: 7,
    image: images.babyMonitor,
    name: 'Babá Eletrônica See, Maxi-Cosi, White',
    price: 629.1,
    quantity: 0,
  },
  {
    id: 8,
    image: images.cueiroUnity,
    name: 'Cueiro Estampado, Papi Textil, Azul, 80cmx50cm',
    price: 21.21,
    quantity: 0,
  },
  {
    id: 9,
    image: images.humidifier,
    name: 'Umidificador Breathe, Maxi-Cosi',
    price: 799,
    quantity: 0,
  },
  {
    id: 10,
    image: images.nailClipper,
    name: 'Cortador De Unha Baby Colors Ricca Azul, Ricca',
    price: 9.56,
    quantity: 0,
  },
  {
    id: 11,
    image: images.soap,
    name: 'Sabonete Liquido Bebe Camomila, Granado, 250ml',
    price: 18.99,
    quantity: 0,
  },
  {
    id: 12,
    image: images.towel,
    name: 'Toalha Felpuda Estampada com Capuz, 90 x 70 cm, Azul Carros',
    price: 31.9,
    quantity: 0,
  },
  {
    id: 13,
    image: images.babySeat,
    name: '1 Cota - Bebê Conforto Solare Tutti Baby',
    price: 25,
    quantity: 0,
    showInCarousel: true,
  },
  {
    id: 14,
    image: images.spoon,
    name: 'Buba Colher Dosadora, Azul',
    price: 30,
    quantity: 0,
    showInCarousel: true,
  },
]
